###########################################################################
#                                                                         #
#   Copyright (c) Microsoft Corporation. All rights reserved.             #
#                                                                         #
#   This code is licensed under the MIT License (MIT).                    #
#                                                                         #
###########################################################################

name: Sign PowerShell Scripts
description: Sign PowerShell scripts in the Containers-Toolkit repository

inputs:
  Directory:
    description: The directory containing files to sign
    default: "./"
    required: false
  AzureKeyVaultUrl:
    description: "The URL to an Azure Key Vault."
    required: true
  AzureKeyVaultClientId:
    description: "The Client ID (Application ID) to authenticate to the Azure Key Vault."
    required: true
  AzureKeyVaultClientSecret:
    description: "The client secret of your Azure application to authenticate to the Azure Key Vault."
    required: true
  AzureKeyVaultTenantId:
    description: "The Tenant Id to authenticate to the Azure Key Vault."
    required: true
  AzureKeyVaultCertificate:
    description: "The name of the certificate in Azure Key Vault."
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup .NET Core # Required to execute ReportGenerator
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
        dotnet-quality: "ga"

    - uses: actions/cache@v3
      with:
        path: ~/.dotnet/tools
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-azuresigntool

    - name: Install AzureSignTool
      shell: pwsh
      run: dotnet tool install --global AzureSignTool

    # https://learn.microsoft.com/en-us/windows/msix/desktop/cicd-keyvault
    # https://learn.microsoft.com/en-us/previous-versions/windows/hardware/design/dn653556(v=vs.85)
    - name: Sign PowerShell scripts
      shell: pwsh
      run: |
        $akvParams = @{
            'AzureKeyVaultClientId'     = ${{ inputs.AzureKeyVaultClientId }}
            'AzureKeyVaultTenantId'     = ${{ inputs.AzureKeyVaultTenantId }}
            'AzureKeyVaultClientSecret' = ${{ inputs.AzureKeyVaultClientSecret }}
            'AzureKeyVaultUrl'          = ${{ inputs.AzureKeyVaultUrl }}
            'AzureKeyVaultCertificate'  = ${{ inputs.AzureKeyVaultCertificate }}
        }
        .github/actions/sign-scripts/sign-scripts.ps1 -Directory "${{ inputs.Directory }}" @akvParams

    # # Commit the changes
    # - name: Commit changes
    #   shell: bash
    #   run: |
    #     # configure user
    #     git config --global user.name "${{ github.actor }}"
    #     git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    #     # Stage and commit signed files
    #     git add .
    #     git commit -m 'Sign PowerShell scripts'

    #     # push the commit back up to source GitHub repository
    #     git push

    # https://tech.nicolonsky.ch/github-actions-powershell-signing/
    # - name: Import code signing certificate
    #   shell: powershell
    #   run: |
    #     $pfxCertFilePath = Join-Path -Path $PSScriptRoot -ChildPath "CodeSigningCertificate.pfx"
    #     Set-Content -Value $([System.Convert]::FromBase64String(${{ inputs.BASE64_PFX)) -Path $pfxCertFilePath -Encoding B }}yte
    #     $codeSigningCert = Import-PfxCertificate -FilePath $pfxCertFilePath -Password $(${{ inputs.PFX_PASSWORD | ConvertTo-SecureString -AsPlainText -Force) -CertStoreLocation Cert:\CurrentUser }}\My
    #   env:
    #     BASE64_PFX: ${{ secrets.BASE64_PFX }}
    #     PFX_PASSWORD: ${{ secrets.PFX_PASSWORD }}

    # - name: Sign PowerShell scripts
    #   shell: powershell
    #   run: |
    #     # remove git dir from checked out repo
    #     Get-ChildItem -Path "." -Filter ".git*" -Force | ForEach-Object {Remove-Item -Path $_.FullName -Recurse -Force}
    #     # Get scripts to sign
    #     $scripts = Get-ChildItem -Path . -Recurse -ErrorAction Stop | Where-Object {$_.name -match "ps[d|m]?1(xml)?"}
    #     # load cert
    #     $codeSigningCert = Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert | Select-Object -First 1
    #     foreach ($script in $scripts) {
    #         try {
    #               $scriptContent = Get-Content -Path $script.FullName
    #               Write-Output "Signing script `"$($script.Name)`" with certificate `"$($codeSigningCert.Thumbprint)`""
    #               # sign script
    #               $null = Set-AuthenticodeSignature -Certificate $codeSigningCert -FilePath $script.FullName -TimestampServer "http://timestamp.comodoca.com/rfc3161"
    #         }
    #         catch {
    #             Write-Error $_
    #         }
    #     }

    # - name: Publish signed scripts to GitHub Artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: ${{ inputs.output_artifact_name }}
    #     path: .
