###########################################################################
#                                                                         #
#   Copyright (c) Microsoft Corporation. All rights reserved.             #
#                                                                         #
#   This code is licensed under the MIT License (MIT).                    #
#                                                                         #
###########################################################################

name: Sign PowerShell Scripts
description: Sign PowerShell scripts in the Containers-Toolkit repository

inputs:
  Directory:
    description: The directory containing files to sign
    default: "./"
    required: false
  AzureKeyVaultUrl:
    description: "The URL to an Azure Key Vault."
    required: true
  AzureKeyVaultClientId:
    description: "The Client ID (Application ID) to authenticate to the Azure Key Vault."
    required: true
  AzureKeyVaultClientSecret:
    description: "The client secret of your Azure application to authenticate to the Azure Key Vault."
    required: true
  AzureKeyVaultTenantId:
    description: "The Tenant Id to authenticate to the Azure Key Vault."
    required: true
  AzureKeyVaultCertificate:
    description: "The name of the certificate in Azure Key Vault."
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup .NET Core # Required to execute ReportGenerator
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
        dotnet-quality: "ga"

    - uses: actions/cache@v3
      with:
        path: ~/.dotnet/tools
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-azuresigntool

    - name: Install AzureSignTool
      shell: pwsh
      run: dotnet tool install --global AzureSignTool

    # https://learn.microsoft.com/en-us/windows/msix/desktop/cicd-keyvault
    # https://learn.microsoft.com/en-us/previous-versions/windows/hardware/design/dn653556(v=vs.85)
    - name: Sign PowerShell scripts
      shell: pwsh
      run: |
        $akvParams = @{
            'AzureKeyVaultClientId'     = ${{ inputs.AzureKeyVaultClientId }}
            'AzureKeyVaultTenantId'     = ${{ inputs.AzureKeyVaultTenantId }}
            'AzureKeyVaultClientSecret' = ${{ inputs.AzureKeyVaultClientSecret }}
            'AzureKeyVaultUrl'          = ${{ inputs.AzureKeyVaultUrl }}
            'AzureKeyVaultCertificate'  = ${{ inputs.AzureKeyVaultCertificate }}
        }
        .github/actions/sign-scripts/sign-scripts.ps1 -Directory "${{ inputs.Directory }}" @akvParams
