name: Create Container Toolkit Release




# Checkout from the repository
# Update the module version
# Sign the module scripts
# Sign the repository scripts
  # - remove the unnecessary dirs eg .git/, .github
