name: DevSkim

on:
  push:
    branches: ["main", "releases/**"]
  pull_request:
    branches: ["main", "releases/**"]

jobs:
  lint:
    name: DevSkim
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1
        with:
          # Relative path in $GITHUB_WORKSPACE for DevSkim to Scan
          directory-to-scan: '.\containers-toolkit'
          ignore-globs: "en-US/**"

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif
