# https://tech.nicolonsky.ch/github-actions-powershell-signing/

name: Sign PowerShell Scripts
on:
  push:
    branches:
      - "releases/**"

jobs:
  sign-scripts:
    name: Sign and archives Containers-Toolkit PowerShell scripts
    runs-on: windows-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: Install AzureSignTool
        if: 
        shell: pwsh
        run: dotnet tool install --global AzureSignTool

      # https://learn.microsoft.com/en-us/windows/msix/desktop/cicd-keyvault
      # https://learn.microsoft.com/en-us/previous-versions/windows/hardware/design/dn653556(v=vs.85)
      - name: Sign PowerShell scripts
        shell: pwsh
        run: |
          # Get scripts to sign
          $scripts = Get-ChildItem -Path . -Recurse -ErrorAction Stop | Where-Object { $_.name -match "ps[d|m]?1(xml)?" }

          # Sign the scripts
          foreach ($script in $scripts) {
              Write-Host "Signing file: $_.Name"
              $filePath = $_.FullName
              & AzureSignTool sign -kvu "${{ secrets.AzureKeyVaultUrl }}" `
                  -kvi "${{ secrets.AzureKeyVaultClientId }}" `
                  -kvs "${{ secrets.AzureKeyVaultClientSecret }}" `
                  -kvc ${{ secrets.AzureKeyVaultName }} `
              -tr http://timestamp.digicert.com -v $filePath
          }

      # Commit the changes
      - name: Commit changes
        shell: bash
        run: |
          # configure user
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          # Stage and commit signed files
          git add .
          git commit -m 'Sign PowerShell scripts'

          # push the commit back up to source GitHub repository
          git push

# env:
#   # MODULE_ARTIFACT: CTK.Module.Scripts
#   # REPO_ARTIFACT: CTK.Scripts
#   # SIGNED_MODULE_ARTIFACT: CTK.Module.Scripts.Signed
#   # SIGNED_REPO_ARTIFACT: CTK.Scripts.Signed
#   SRC_DIRECTORY: .\Containers-Toolkit\

# jobs:
#   sign_scripts:
#     name: Sign and archives Containers-Toolkit PowerShell scripts
#     runs-on: windows-latest
#     steps:
#     - name: Download unsigned module scripts from artifact
#       uses: actions/download-artifact@v4
#       with:
#         name: ${{ env.MODULE_ARTIFACT }}

#     - name:  Sign and archive signed module scripts
#       uses: ./.github/actions/sign-scripts
#       with:
#         input_artifact_name: ${{ env.MODULE_ARTIFACT }}
#         output_artifact_name: ${{ env.SIGNED_MODULE_ARTIFACT }}

#     - name: Download unsigned repository scripts from artifact
#       uses: actions/download-artifact@v4
#       with:
#         name: ${{ env.REPO_ARTIFACT }}

#     - name: Sign and archive signed repository scripts
#       uses: ./.github/actions/sign-scripts
#       with:
#         input_artifact_name: ${{ env.REPO_ARTIFACT }}
#         output_artifact_name: ${{ env.SIGNED_REPO_ARTIFACT }}
